<article class="formContainer">
	<h2>Please login with your admin credentials.</h2>
	<?php 
		if( !empty($this->customSuccessMessages) ) {
			echo "<ul class='success customMessages'>";
			foreach( $this->customSuccessMessages as $successMessage ) echo "<li>" . $successMessage . "</li>";
			echo "</ul>";
		}

		if( !empty($this->customErrorMessages) ) {
			echo "<ul class='error customMessages'>";
			foreach( $this->customErrorMessages as $error ) echo "<li>" . $error . "</li>";
			echo "</ul>";
		}

		echo $this->loginForm;
	?>
</article>