<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class=""> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>Admin Application</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <link rel="stylesheet" href="/admin_files/styles/css/master.css">

  <script src="/app_files/js/libs/modernizr-2.0.6.min.js"></script>
</head>

<body>
	<header>
		<h1><!-- isabellacollection.com --> Admin</h1>
		<nav>
			<ul>
				<li><a href="/admin/user/edit">Admin Overview</a></li>
				<li><a href="/admin/collections">Manage Collections</a></li>
				<li><a href="/admin/designers">Manage Designers</a></li>
				<li><a href="/admin/index/logout">Logout</a></li>
			</ul>
		</nav>
	</header>
	<section>
		<?= $this->layout()->content ?>
	</section>
	<footer>
		<p>&copy; company</p>
	</footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/app/js/libs/jquery-1.6.2.min.js"><\/script>')</script>


  <!-- scripts concatenated and minified via ant build script-->
  <script defer src="/admin_files/js/plugins.js"></script>
  <script defer src="/admin_files/js/script.js"></script>
  <!-- end scripts-->

	
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->  
</body>
</html>
