<!-- <h2>Collections</h2> -->
<p><a href="/admin/collections/">&lsaquo; Back to Collections</a></p>
<?php 
if( !empty($this->customSuccessMessages) ) {
	echo "<article>";
	echo "<ul class='success customMessages'>";
	foreach( $this->customSuccessMessages as $successMessage ) echo "<li>" . $successMessage . "</li>";
	echo "</ul>";
	echo "</article>";
}

if( !empty($this->customErrorMessages) ) {
	echo "<article>";
	echo "<ul class='error customMessages'>";
	foreach( $this->customErrorMessages as $error ) echo "<li>" . $error . "</li>";
	echo "</ul>";
	echo "</article>";
}
?>

<article>
	<dl class="viewDetails">
		<dt>Collection:</dt>
		<dd><h3>&ldquo;<?php echo $this->collectionDataArr['name'] ?>&rdquo;</h3></dd>
		<dt>Status:</dt>
		<dd><?php echo ($this->collectionDataArr['is_archived']) ? "Archived" : "Active" ?></dd>
		<dt>Created:</dt>
		<dd><?php echo $this->collectionDataArr['create_date'] ?></dd>
		<?php if($this->collectionDataArr['is_archived']) { ?>
		<dt>Archived:</dt>
		<dd><?php echo $this->collectionDataArr['archive_date'] ?></dd>
		<?php } ?>
		<dt>Full size:</dt>
		<dd><img src="/app_files/img/collections/<?php echo $this->collectionDataArr['full_filename'] ?>" alt="<?php echo $this->collectionDataArr['full_filename'] ?>" /></dd>
		<dt>Thumbnail:</dt>
		<dd><img src="/app_files/img/collections/<?php echo $this->collectionDataArr['thumb_filename'] ?>" alt="<?php echo $this->collectionDataArr['thumb_filename'] ?>" /></dd>
	</dl>
	<?php if(!$this->collectionDataArr['is_archived']) { ?>
	<p><a href="/admin/collections/edit/collectionID/<?php echo $this->collectionDataArr['id'] ?>">Edit Collection</a></p>
	<?php } ?>
</article>

<?php if(!$this->collectionDataArr['is_archived']) { ?>
<article class="formContainer">
	<h3>Add new item to this collection</h3>
	<?php echo $this->addItemForm ?>
</article>
<?php } ?>

<article class="listingContainer itemsContainer">
	<h3>Items in this collection (<?php echo count($this->itemDataArr) ?>)</h3>
	<?php if(!empty($this->itemDataArr)) { ?>
	<table>
		<thead>
			<tr>
				<th>photo reference</th>
				<th>stock number</th>
				<th>unit price</th>
				<th class="descriptive">description</th>
				<th class="descriptive">notes</th>
				<th>created</th>
				<?php if(!$this->collectionDataArr['is_archived']) { ?>
				<th>&nbsp;</th>
				<?php } ?>
			</tr>
		</thead>
		<tbody>
			<?php

			foreach( $this->itemDataArr as $item ) {
				echo "\n\t\t<tr>";
				echo "\n\t\t\t<td>" . $item['photo_reference'] . "</td>";
				echo "\n\t\t\t<td>" . $item['stock_number'] . "</td>";
				echo "\n\t\t\t<td>" . $item['unit_price'] . "</td>";
				echo "\n\t\t\t<td class='textContent'>" . $item['description'] . "</td>";
				echo "\n\t\t\t<td class='textContent'>" . $item['notes'] . "</td>";
				echo "\n\t\t\t<td>" . $item['create_date'] . "</td>";
				if( !$this->collectionDataArr['is_archived'] ) {
					echo "\n\t\t\t<td>";
					echo "\n\t\t\t\t<a href='/admin/items/edit/collectionID/" . $this->collectionDataArr['id'] . "/itemID/" . $item['id'] . "'>edit item</a>";
					echo "\n\t\t\t\t<a class='negative' href='/admin/items/delete/collectionID/" . $this->collectionDataArr['id'] . "/itemID/" . $item['id'] . "'>delete item</a>";
					echo "\n\t\t\t</td>";
				} else {
					echo "\n\t\t\t<td>&nbsp;</td>";
				}
				echo "\n\t\t</tr>";
			}

			?>
		</tbody>
	</table>
	<?php } else { ?>
		<p>No items found.</p>
	<?php } ?>
</article>