<!-- <h2>Collections</h2> -->
<article class="listingContainer designersContainer">
	<h3>Pending Designers (<?php echo count($this->pendingDesignersDataArr) ?>)</h3>
	<?php if(!empty($this->pendingDesignersDataArr)) { ?>
	<table>
		<thead>
			<tr>
				<th>Date Applied</th>
				<th>Business Name</th>
				<th>Owner</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php
			// loop through the pending designer data array
			foreach( $this->pendingDesignersDataArr as $designer ) {?>
				<tr>
					<td><?php echo $designer['create_date'] ?></td>
					<td><?php echo $designer['business_name'] ?></td>
					<td><?php echo $designer['owner_first_name'] . " " . $designer['owner_last_name'] ?></td>
					<td><a href="/admin/designers/view/designerID/<?php echo $designer['id'] ?>">View</a></td>
				</tr>
			<?php
			}
			?>
		</tbody>
	</table>
	<?php } else { ?>
		<p>No designers pending approval.</p>
	<?php } ?>

	<h3>Approved Designers (<?php echo count($this->approvedDesignersDataArr) ?>)</h3>
	<?php if(!empty($this->approvedDesignersDataArr)) { ?>
	<table>
		<thead>
			<tr>
				<th>Date Applied</th>
				<th>Business Name</th>
				<th>Owner</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php
			// loop through the pending designer data array
			foreach( $this->approvedDesignersDataArr as $designer ) {?>
				<tr>
					<td><?php echo $designer['create_date'] ?></td>
					<td><?php echo $designer['business_name'] ?></td>
					<td><?php echo $designer['owner_first_name'] . " " . $designer['owner_last_name'] ?></td>
					<td><a href="/admin/designers/view/designerID/<?php echo $designer['id'] ?>">View</a></td>
				</tr>
			<?php
			}
			?>
		</tbody>
	</table>
	<?php } else { ?>
		<p>No designers have been approved.</p>
	<?php } ?>
	
	<h3>Denied Designers (<?php echo count($this->deniedDesignersDataArr) ?>)</h3>
	<?php if(!empty($this->deniedDesignersDataArr)) { ?>
	<table>
		<thead>
			<tr>
				<th>Date Applied</th>
				<th>Business Name</th>
				<th>Owner</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php
			// loop through the pending designer data array
			foreach( $this->deniedDesignersDataArr as $designer ) {?>
				<tr>
					<td><?php echo $designer['create_date'] ?></td>
					<td><?php echo $designer['business_name'] ?></td>
					<td><?php echo $designer['owner_first_name'] . " " . $designer['owner_last_name'] ?></td>
					<td><a href="/admin/designers/view/designerID/<?php echo $designer['id'] ?>">View</a></td>
				</tr>
			<?php
			}
			?>
		</tbody>
	</table>
	<?php } else { ?>
		<p>No designers have been denied.</p>
	<?php } ?>
</article>
