<!-- <h2>Collections</h2> -->
<p><a href="/admin/designers/">&lsaquo; Back to Designers</a></p>

<article>
	<dl class="viewDetails designerDetails">
		<?php $designer = $this->designerDataArr ?>
		<dt>Status:</dt>
		<dd class="status"><?php echo $designer['status'] ?></dd>
		<dt>Date Applied:</dt>
		<dd><?php echo $designer['create_date'] ?></dd>
		<dt>Business Name:</dt>
		<dd><?php echo $designer['business_name'] ?></dd>
		<dt>Owner:</dt>
		<dd><?php echo $designer['owner_first_name'] . " " . $designer['owner_last_name'] ?></dd>
		<dt>Email:</dt>
		<dd><?php echo $designer['email'] ?></dd>
		<dt>Address:</dt>
		<dd>
		<?php
			echo $designer['address'] . "<br />";
			echo $designer['city'] . ", " . $designer['state'] . " " . $designer['zip'];
		?>
		</dd>
		<dt>Phone Number:</dt>
		<dd><?php echo $designer['phone_number'] ?></dd>
		<dt>Fax Number:</dt>
		<dd><?php echo (!$designer['fax_number']) ? 'None provided' : $designer['fax_number'] ?></dd>
		<dt>Tax Document:</dt>
		<?php
		if( $designer['tax_id_delivery'] == 'fax') { 
		?>
		<dd>Will fax documentation</dd>
		<?php
		} else {
		?>
		<dd><a href="/app_files/designerDocs/<?php echo $designer['tax_document_filename'] ?>" target="_blank">View Tax Document</a></dd>
		<?php
		}
		?>
		<?php
		switch($designer['status']) 
		{
			case 'pending': 
			?>
				<dt>This designer is "pending" approval. Please take an action. An email will be sent to notify the designer of their udpated status.</dt>
				<dd>
					<ul class="buttonCollection">
						<li><a class="positive" href="/admin/designers/approve/designerID/<?php echo $designer['id'] ?>">Approve Designer</a></li>
						<li><a class="negative" href="/admin/designers/deny/designerID/<?php echo $designer['id'] ?>">Deny Designer</a></li>
					</ul>
				</dd>
			<?php
				break;
				
			case 'approved':
			?>
				<dt>This designer has been approved. You can deny access as needed. An email will be sent to notify the designer of their udpated status.</dt>
				<dd>
					<ul class="buttonCollection">
						<li><a class="negative" href="/admin/designers/deny/designerID/<?php echo $designer['id'] ?>">Deny Designer</a></li>
					</ul>
				</dd>
			<?php
				break;
				
			case 'denied':
			?>
				<dt>This designer has been denied access. You can grant access. An email will be sent to notify the designer of their udpated status.</dt>
				<dd>
					<ul class="buttonCollection">
						<li><a class="positive" href="/admin/designers/approve/designerID/<?php echo $designer['id'] ?>">Approve Designer</a></li>
					</ul>
				</dd>
			<?php
				break;
				
			default:
		}
		?>
	</dl>
</article>