<p><a href="/admin/user/edit/">&lsaquo; Back to Admin Overview</a></p>

<article class="formContainer">
	<h2>Change Admin Password</h2>
	<?php
		if( !empty($this->customSuccessMessages) ) {
			echo "<ul class='success customMessages'>";
			foreach( $this->customSuccessMessages as $successMessage ) echo "<li>" . $successMessage . "</li>";
			echo "</ul>";
		}

		if( !empty($this->customErrorMessages) ) {
			echo "<ul class='error customMessages'>";
			foreach( $this->customErrorMessages as $error ) echo "<li>" . $error . "</li>";
			echo "</ul>";
		}

		// show the add admin user form
		echo $this->updateAdminPasswordForm; 
	 ?>		
</article>